# Generated by Django 4.1.4 on 2023-02-17 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('designation', models.CharField(max_length=255, null=True)),
                ('Job_descritption', models.CharField(max_length=2000, null=True)),
                ('github_link', models.CharField(blank=True, max_length=255, null=True)),
                ('google_plus_link', models.CharField(blank=True, max_length=255, null=True)),
                ('linked_in_link', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(null=True, upload_to='profiles/')),
                ('level', models.IntegerField(default=3)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication', models.TextField(max_length=5000, null=True)),
                ('link', models.CharField(blank=True, max_length=1000, null=True)),
                ('journal', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
