# Generated by Django 4.1.4 on 2023-02-20 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cellmarker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geneSymbol', models.CharField(blank=True, max_length=255, null=True)),
                ('species', models.CharField(blank=True, max_length=255, null=True)),
                ('tissueType', models.CharField(blank=True, max_length=255, null=True)),
                ('cancerType', models.CharField(blank=True, max_length=255, null=True)),
                ('cellName', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose_id', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('gene_id', models.CharField(blank=True, max_length=1000, null=True)),
                ('gene_symbol', models.CharField(blank=True, max_length=1000, null=True)),
                ('p_value', models.FloatField(max_length=100, null=True)),
                ('adj_pvalue', models.FloatField(max_length=100, null=True)),
                ('count', models.IntegerField(null=True)),
                ('organism', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Enrich',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pmid', models.CharField(blank=True, max_length=255, null=True)),
                ('enrichment', models.CharField(blank=True, max_length=255, null=True)),
                ('count_total', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Remembprot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pmid', models.CharField(blank=True, max_length=255, null=True)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('paper', models.CharField(blank=True, max_length=255, null=True)),
                ('organism', models.CharField(blank=True, max_length=255, null=True)),
                ('CellOrtissue', models.CharField(blank=True, max_length=255, null=True)),
                ('disease', models.CharField(blank=True, max_length=255, null=True)),
                ('profileOrDifex', models.CharField(blank=True, max_length=20, null=True)),
                ('contxtOfIdent', models.CharField(blank=True, max_length=20, null=True)),
                ('contxtOfDiferentialREG', models.CharField(blank=True, max_length=20, null=True)),
                ('test', models.CharField(blank=True, max_length=255, null=True)),
                ('control', models.CharField(blank=True, max_length=255, null=True)),
                ('foldchange', models.CharField(blank=True, max_length=255, null=True)),
                ('expression', models.CharField(blank=True, max_length=255, null=True)),
                ('protienExtractMethod', models.CharField(blank=True, max_length=255, null=True)),
                ('geneSymbol', models.CharField(blank=True, max_length=255, null=True)),
                ('geneID', models.CharField(blank=True, max_length=255, null=True)),
                ('ontology', models.CharField(blank=True, max_length=255, null=True)),
                ('membraneType', models.CharField(blank=True, max_length=255, null=True)),
                ('peripheral', models.CharField(blank=True, max_length=255, null=True)),
                ('isTrans', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
