# Generated by Django 4.1.4 on 2023-02-22 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rememb_prot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remembprot',
            name='membraneType',
        ),
        migrations.RemoveField(
            model_name='remembprot',
            name='ontology',
        ),
        migrations.RemoveField(
            model_name='remembprot',
            name='peripheral',
        ),
    ]
