# Generated by Django 4.1.4 on 2023-02-24 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rememb_prot', '0004_alter_cellmarker_genesymbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cellmarker',
            name='geneSymbol',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
