# Generated by Django 4.1.4 on 2023-02-24 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rememb_prot', '0005_alter_cellmarker_genesymbol'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cellmarker',
        ),
    ]
