# Generated by Django 4.1.4 on 2023-02-24 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rememb_prot', '0006_delete_cellmarker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cellmarker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geneSymbol', models.CharField(blank=True, max_length=255, null=True)),
                ('species', models.CharField(blank=True, max_length=255, null=True)),
                ('tissueType', models.CharField(blank=True, max_length=255, null=True)),
                ('cancerType', models.CharField(blank=True, max_length=255, null=True)),
                ('cellName', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
