# Generated by Django 4.2.2 on 2023-08-28 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rememb_prot', '0007_cellmarker'),
    ]

    operations = [
        migrations.AddField(
            model_name='dose',
            name='method',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
