# Generated by Django 4.2.2 on 2023-08-28 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rememb_prot', '0008_dose_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dose',
            name='method',
        ),
        migrations.AddField(
            model_name='enrich',
            name='method',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
